### ISSUE TITLE
Consider using a lookup table for gmult

### ISSUE THREAD

**Issue by dhuertas** [cryptico-org/aes#1]
Hi!

This is more of a suggestion than an issue. Have you considered using a lookup table to replace the gmult operation? In C it adds a speed boost in case you're not using the AES instruction set, but I'm not sure how that would work in Typescript/JS.

Cheers,

Dani Huertas

**Comment by uamanager** [comment]
Hi!

I used it in first versions, going to use it in the future. 
But I'll test speed/performance first. But seems like It'll be better.

Thanks for suggestion)

**Comment by uamanager** [comment]
Hey, 
I finally found time to check what's better gmult or lookup table. By my subjective tests performance while using lookup tables is slightly better, but the issue is that this lookup table – +450kB, which is not really appropriate for web apps, I think.
Thanks for your suggestion.

**Comment by dhuertas** [comment]
Interesting finding nonetheless. Thank you for checking out.
